### PR TITLE
Update lotterynew.java

### PR DESCRIPTION
**Pull request by Xan1924**
sooooo many mistakes
I think I fixed most of them
added a new thing

### CODE REVIEW

**Comment by Xan1924** [comment]
The stock system is really buggy

**Comment by Redstone-ray** [comment]
Fix the bugs, without creating more bugs

**Review by Redstone-ray — CHANGES_REQUESTED** [review]
You need to insert } to complete the class

**Comment by Redstone-ray** [comment]
Also, you need system.out.println, not just out.println

**Comment by Redstone-ray** [comment]
I would still suggest to use system.out.println, since that could be easier to achieve by sysout

**Comment by Redstone-ray** [comment]
I just found out the >< are facing wrong direction. I fixed the stock

**Review by Redstone-ray — APPROVED** [review]

**Review by Redstone-ray — APPROVED** [review]

**Comment by Xan1924** [comment]
The new code doesn't work on the my java

**Comment by Xan1924** [comment]
nevermind

**Comment by Xan1924** [comment]
new record $8944070491913.38

**Comment by Xan1924** [comment]
Shut up, I did what you said

**Pull request merged**
