### PR TITLE
Add illnesses

### PR DESCRIPTION
**Pull request by Redstone-ray**
Get too excited when you earn too much money. and get sick.

### CODE REVIEW

**Comment by Xan1924** [comment]
tommorow

**Comment by Xan1924** [comment]
Can I delete one of the decimal formats? It it the same as the first one.

**Comment by Xan1924** [comment]
Also, are you going to merge lottery to master?

**Comment by Xan1924** [comment]
What do you mean by get too excited and get sick?

**Comment by Xan1924** [comment]
NumberFormat e = new DecimalFormat("#0.00");
can I delete this?

**Comment by Redstone-ray** [comment]
> NumberFormat e = new DecimalFormat("#0.00");
> can I delete this?

Yes, use one instead. And also, just text me

**Comment by Redstone-ray** [comment]
> What do you mean by get too excited and get sick?

If you get a large amount of money in a short period of time: for ex: win lottery 2times in a row, stock got increased by 10%
Your heath(start at 100) decreases.
50< means hospital, you must roll dice / pay to heal yourself

**Comment by Redstone-ray** [comment]
#5

**Pull request merged**
