### PR TITLE
Clean up the code, merge some code into variables

### PR DESCRIPTION
**Pull request by Redstone-ray**
Some codes are repeated, try to fix them

### CODE REVIEW

**Comment by Xan1924** [comment]
Fine I’ll do it

**Comment by Redstone-ray** [comment]
@Xan1924 Do you have snapchat/insta/messager/fb/discord etc?

**Comment by Xan1924** [comment]
no I don't

**Comment by Xan1924** [comment]
lol, look at my final score in the game $13101976689130332
it was too high that it didn't display the levels anymore

**Comment by Redstone-ray** [comment]
> lol, look at my final score in the game $13101976689130332
> it was too high that it didn't display the levels anymore

The fk how did you get that high? Also, you have no social media?

**Pull request merged**
